name: Lint Check
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/make.yml'
      - 'Makefile'

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Build step
        run: make -n

      - name: Dep
        run: sudo apt update && sudo apt install libcap-dev libseccomp-dev -y

      - name: Build
        run: make
