name: Lint Check
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/make.yml'
      - 'Makefile'

jobs:
  make:
    runs-on: ubuntu-latest

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Build step
        run: make -n

      - name: Build
        run: make
